create capanames
ecodomen/nsreg-watcher pull request #124
Opened 2023-12-19 15:35 UTC by Mihailprogram

парсер для https://capnames.ru/ #110

2023-12-22 04:34 UTC, mrezvova commented
Привет! 
Спасибо за выполненную задачу, очень ценим твой вклад!
Готовы пригласить тебя при ближайшем онбординге, обычно по субботам в 15 мск.
Сообщи, пожалуйста, свой контакт в телеграме здесь или по почте info@ecodomen.ru со ссылкой на твой PR, чтобы мы опознали кто это.

Увидимся на встрече!

2024-01-03 19:20 UTC, poligrafo commented
нужно исправить предупреждение линтера

2024-01-04 14:27 UTC, aleksey-vasilev commented on src/grabber/nsreg/spiders/nsreg_capnames.py
> +        return self.component.parse(response)
Нужно добавить пустую строчку чтобы линтер не ругался

2024-01-04 14:27 UTC, aleksey-vasilev requested changes
Исправить в соосветствии с PEP8

2024-01-13 11:42 UTC, closed without merging