add parser for elastichosting #94
ecodomen/nsreg-watcher pull request #133
Opened 2023-12-21 18:43 UTC by databorodata

https://github.com/ecodomen/nsreg-watcher/issues/94

2023-12-22 05:45 UTC, mrezvova commented
Привет!
Ты сделал хороший парсер, но такой вид спайдеров уже устарел в нашем проекте
Мы поменяли структуру парсеров, пример можешь посмотреть в README.md(там целая инструкция)

2023-12-22 12:48 UTC, databorodata commented
Привет! Ага, вижу. Оки, переделаю

2023-12-23 11:43 UTC, databorodata commented
Поправил. Случай для парсинга не простой. Поэтому пришлось изголится с путём... Я проверил, всё парсится.

2023-12-24 10:14 UTC, databorodata commented
посмотрел на упавшие проверки, там ругается не на тот файл который добавлял.

2024-01-04 14:21 UTC, aleksey-vasilev requested changes

2024-01-04 14:21 UTC, aleksey-vasilev commented on src/grabber/nsreg/spiders/nsreg_elastichosting.py
> +    start_urls = ["https://elastichosting.ru/domain/pricing"]
Привет! Ты сделал хороший парсер, но данная страница в настоящий момент на сайте отсутствует - попробуй найти данные в другом разделе сайта

2024-01-05 10:06 UTC, databorodata commented on src/grabber/nsreg/spiders/nsreg_elastichosting.py
> +    start_urls = ["https://elastichosting.ru/domain/pricing"]
Поправил. Они изменили https://elastichosting.ru на https://my.elastichosting.ru . Проверил, всё парсится

2024-01-05 19:29 UTC, aleksey-vasilev commented
Спасибо за выполненную задачу, очень ценим твой вклад!
Готовы пригласить тебя при ближайшем онбординге, обычно по субботам в 15 мск.
Сообщи, пожалуйста, свой контакт по почте [info@ecodomen.ru](mailto:info@ecodomen.ru) со ссылкой на твой PR, чтобы мы опознали кто это.

Увидимся на встрече!

2024-01-05 19:29 UTC, aleksey-vasilev approved these changes

2024-01-05 19:29 UTC, merged

2024-01-10 11:13 UTC, databorodata commented
> Спасибо за выполненную задачу, очень ценим твой вклад! Готовы пригласить тебя при ближайшем онбординге, обычно по субботам в 15 мск. Сообщи, пожалуйста, свой контакт в телеграме здесь или по почте [info@ecodomen.ru](mailto:info@ecodomen.ru) со ссылкой на твой PR, чтобы мы опознали кто это.
> 
> Увидимся на встрече!

Я отправил на почту, никто не ответил. Телеграмм https://t.me/data_borodata