Add space removal in find_price
ecodomen/nsreg-watcher pull request #231
Opened 2024-01-16 13:19 UTC by yogorus

Добавил строчку с удалением пробелов в функции **find_price**, т.к мне кажется, что это лучший вариант решения проблемы с пробелами внутри строки.
Т.к используется метод *sub* из регулярок, то он удалит любые пробельные символы, в т.ч и юникодовские.
Вариант с **translate** из *xpath* не всегда работает, т.к в строке могут находиться и юникодовские пробелы типа **"\xa0"**, так и обычные " ". Такой случай оказался в **capnames.ru**
Плюс такой вариант не должен ломать случаи, когда мы в регулярке ищем пробел, т.к иногда это лучший способ найти цену на сайте. Получаем цену с пробелом из html и затем уже find_price приводит её в порядок.
Спайдеры, где используется translate, должны остаться исправными

2024-01-16 13:55 UTC, rsolovyeaws commented
> Вариант с **translate** из _xpath_ не всегда работает, т.к в строке могут находиться и юникодовские пробелы типа **"\xa0"**, так и обычные " ". Такой случай оказался в **capnames.ru**

translate \xa0 тоже убирает, просто нужно его указать translate(..., "\xa0 ", "") уберет и \xa0 и " "

2024-01-16 14:21 UTC, yogorus commented
> > Вариант с **translate** из _xpath_ не всегда работает, т.к в строке могут находиться и юникодовские пробелы типа **"\xa0"**, так и обычные " ". Такой случай оказался в **capnames.ru**
> 
> translate \xa0 тоже убирает, просто нужно его указать translate(..., "\xa0 ", "") уберет и \xa0 и " "
> 
> просто если переписать find_price, нужно переписывать регулярки во всех парсерах, которые ожидают пробел, а когда используешь translate ты в этом парсере ожидаешь что не будет пробела и пишешь регулярку с расчетом на это.

Так зачем переписывать регулярки? Регулярка найдет строку с пробелом, передаст её в наш базовый компонент, дальше find_price достанет первую группу из регулярки, где будет строка с пробелом и потом просто уберет оттуда все пробелы. Ничего не ломается же.

2024-01-23 13:13 UTC, t1ooo commented
Проверил.
Само изменение ничего не ломает.
Если переписывать парсеры, где используеться xpath translate, надо переписывать regxp'ы в них.
Но стоит ли их вообще переписывать, если и так всё работает?
Если только взять это изменение на будущее и прописать гдё-нибудь, как работать с пробелами в ценах.
Сомнения.

2024-01-27 10:51 UTC, aleksey-vasilev requested changes
Ломает только один единственный парсер nsreg_namebit.py. Надо посмотреть что там не так, а так я бы апрувнул

2024-01-27 10:57 UTC, merged