Add migration: regcomp
ecodomen/nsreg-watcher pull request #25
Opened 2023-07-26 04:48 UTC by anna-p706

Добавляет создание таблицы regcomp в миграцию

2023-07-27 06:47 UTC, rufusnufus requested changes

2023-07-27 06:47 UTC, rufusnufus commented on src/website/catalog/migrations/0001_initial.py
> +                ('website', models.TextField(blank=True, null=True)),
почему эти field'ы могут быть пустыми или null? вроде такое не должно быть возможно
```suggestion
                ('name', models.CharField(blank=False, max_length=255, null=False, unique=True)),
                ('note1', models.TextField(blank=False, null=False)),
                ('note2', models.TextField(blank=False, null=False)),
                ('city', models.CharField(blank=False, max_length=255, null=False)),
                ('website', models.TextField(blank=False, null=False)),
```

2023-07-27 16:32 UTC, anna-p706 commented on src/website/catalog/migrations/0001_initial.py
> +                ('website', models.TextField(blank=True, null=True)),
проверила с этими изменениями, все отработало корректно

2023-07-28 08:45 UTC, rufusnufus commented on src/website/catalog/migrations/0001_initial.py
> +                ('website', models.TextField(blank=True, null=True)),
а как мы будем скрапить данные с тех провайдеров, у которых нет website?

2023-07-28 15:36 UTC, anna-p706 commented on src/website/catalog/migrations/0001_initial.py
> +                ('website', models.TextField(blank=True, null=True)),
на встрече решили, что везде должно быть False

2023-08-18 06:40 UTC, rufusnufus approved these changes

2023-08-23 18:04 UTC, merged