refactor stiders
ecodomen/nsreg-watcher pull request #48
Opened 2023-08-18 06:32 UTC by poligrafo

1. Написал оставшиеся мультипарсеры по шаблону.
2. Дописал и переписал остающиеся парсеры по шаблону.

2023-08-22 18:12 UTC, mrezvova requested changes

2023-08-22 18:12 UTC, mrezvova commented on src/grabber/nsreg/spiders/multi_site_spider2.py
> +        'http://www.regplanet.ru/price',
http не должно быть, это згачит, что сайт небезопасный, у него нет сертификата
надо исправить везде на https

2023-08-25 09:35 UTC, SergeAvgust approved these changes

2023-08-25 09:36 UTC, SergeAvgust approved these changes

2023-08-25 09:36 UTC, merged